name: Generate Executables

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  exe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
          
      - uses: actions/upload-artifact@v4
        with:
          name: Tot-exporter.exe
          path: src/dist/windows
